id = "angular-snippets"
name = "Angular TypeScript Snippets"
version = "21.0.0"
schema_version = 1
authors = ["hudson-newey", "johnpapa"]
description = "(Unofficial) Angular 21 TypeScript snippets"
repository = "https://github.com/hudson-newey/angular-snippets-for-zed"
# snippets = ["./snippets/angular.json", "./snippets/typescript.json"]
snippets = "./snippets/typescript.json"
